title: Bloggy blog
author: Monti Amaritto
email: amaritto.monti@github.de
description: > # this means to ignore newlines until "baseurl:"
  This is the best blog anyone can read

# social links
twitter_username: amaritto # DO NOT include the @ character, or else the build will fail!
github_username:  monoamro # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
